name: Deploy to Hostinger via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy API and Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Hostinger via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            # Masuk ke direktori utama projek
            cd /home/u134652667/domains/api.ptas.my/nodejs
            
            # Tarik kod baru
            git fetch origin
            git reset --hard origin/main
            
            # Setup dan Compile Backend
            echo "--- Membina Backend ---"
            cd backend
            npm install
            chmod +x node_modules/.bin/tsc
            export GOMAXPROCS=1
            npm run build
            
            # Restart PM2
            pm2 restart e-care-api
            
            # Setup dan Compile Frontend
            echo "--- Membina Frontend ---"
            cd ../frontend
            npm install
            chmod +x node_modules/.bin/vite
            chmod +x node_modules/esbuild/lib/downloaded-@esbuild-linux-x64-esbuild
            export GOMAXPROCS=1
            npm run build
            
            echo "--- Deployment Berjaya! ---"
